WHITE = "white"
BLACK = "black"

ALPHABET = list("abcdefghijklmnopqrstuvwxyz")

KING = "king"
QUEEN = "queen"
ROOK = "rook"
BISHOP = "bishop"
KNIGHT = "knight"
PAWN = "pawn"

# SAN Parsing
SAN_PIECE_ALIASES = {KING: "K", QUEEN: "Q", ROOK: "R", BISHOP: "B", KNIGHT: "N", PAWN: ""}
SAN_CHECK = "+"
SAN_CHECKMATE = "#"
SAN_PROMOTION = "="
SAN_CAPTURE = "x"
SAN_EN_PASSANT = "e.p."
SAN_CASTLE_QUEENSIDE = "0-0-0"
SAN_CASTLE_KINGSIDE = "0-0"

BOARD_WIDTH = BOARD_HEIGHT = 8

START_BOARD = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"

KINGSIDE = "K"
QUEENSIDE = "Q"

VALID_PAWN_PROMOTIONS = [KNIGHT, BISHOP, ROOK, QUEEN]

# FEN Parsing:
FEN_PIECE_ALIASES = {"K": KING, "Q": QUEEN, "R": ROOK, "B": BISHOP, "N": KNIGHT, "P": PAWN}
FEN_COLOUR_ALIASES = {"W": WHITE, "B": BLACK}
FEN_CASTLING_ALIASES = {"K": KINGSIDE, "Q": QUEENSIDE}
FEN_EMPTY_EPTARGET = "-"

# Game results
WHITE_WIN = "1-0"
BLACK_WIN = "0-1"
DRAW = "1/2-1/2"
IN_PROGRESS = "*"

GUI_CAPTION = "Chess"